underscore -> slash
robotont/robotont_navigation pull request #8
Opened 2021-01-27 12:05 UTC by mmaao

2021-01-27 15:21 UTC, kruusamae requested changes

2021-01-27 15:21 UTC, kruusamae commented on launch/move_base.launch
> +  -->
äkki lisaks kommentaari, et prefix rändab antud juhul yaml-faili ja seda võimaldab subst_value

2021-01-27 15:42 UTC, kruusamae approved these changes

2021-01-29 10:34 UTC, Veix123 approved these changes

2021-01-29 11:22 UTC, merged